apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-all
  description: A collection of all the entities, except users, groups, and templates
spec:
  targets:
    - ./components.yaml
