# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backend-team
  description: The team responsible for managing the microservices
spec:
  type: team
  profile:
    displayName: Back End
    email: backend@example.com
  members: [jamesSmi, joeSoap]
  children: []

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jamesSmi
spec:
  profile:
    displayName: James Smith
    email: jamesSmi@example.com
  memberOf: [backend-team]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: joeSoap
spec:
  profile:
    displayName: Joe Soap
    email: joeSoap@example.co.za
  memberOf: [backend-team]
